#lang racket
(require rackunit pict "../main.rkt")
(module+ test
  (define old (make-digraph '("a -> b") #:ortho #t))
  (check-true (digraph-ortho old))
  (check-true (string-contains? (digraph->dot old) "splines=\"ortho\""))
  (check-false (string-contains? (digraph->dot old) "\northo="))
  (check-false (digraph-ortho (make-digraph '("a") #:ortho #f)))
  (check-true (digraph-ortho (digraph (digraph-objects old) #t)))
  (check-true (hash? (digraph-attrs (make-digraph '("a") #:rankdir "LR"))))
  (check-true (digraph-ortho (make-digraph '("a") #:ortho #t #:splines "ortho")))
  (check-exn exn:fail:contract?
             (lambda () (make-digraph '("a") #:ortho #t #:splines "curved")))
  (define a (vertex "a" "A" "box" (hash)))
  (define b (make-vertex "B"))
  (define e (make-edge a b))
  (define cluster (subgraph "group" (list a b e) (hash)))
  (define graph (digraph (list cluster) (hash '#:rankdir "LR")))
  (check-eq? (car (subgraph-objects cluster)) a)
  (check-equal? (vertex-label a) "A")
  (check-equal? (edge-nodes e) (list "a" (vertex-name b)))
  (check-true (pict? (blank 10 10)))
  (when (find-executable-path "dot")
    (check-true (pict? (digraph->pict graph)))
    (check-true (pict? (digraph->pict old)))))
