#lang racket
(require rackunit pict json "../lib/digraph.rkt" "../lib/dot.rkt")
(module+ test
  (for ([definitions (list '(42) '((same-rank)) '(("a" #:label)) '((edge ("a")))
                           '(("a" unexpected)) '((subgraph "x")) '("a ->"))])
    (check-exn exn:fail:contract? (lambda () (make-digraph definitions))))
  (check-exn exn:fail:contract? (lambda () (make-digraph '("a") '("b"))))
  (check-equal? (digraph-objects (make-digraph '(()))) '(()))
  (check-equal? (digraph->dot (make-digraph '(()))) (digraph->dot (make-digraph '())))
  (define graph (make-digraph '((subgraph "first" ("a"))
                                (subgraph "second" ("b"))
                                (same-rank "a")) #:nodesep 1/2))
  (check-equal? (digraph->dot graph) (digraph->dot graph))
  (check-true (string-contains? (digraph->dot graph) "nodesep=\"0.5\""))
  (check-equal? (hash-count (digraph-node-picts graph)) 0)
  (define generated (for/list ([i (in-range 1000)]) (vertex-name (make-vertex "a"))))
  (check-equal? (length (remove-duplicates generated)) 1000)
  (when (find-executable-path "dot")
    (for ([name '("颜色" "123" "graph" "custom-key" "quote\"key")])
      (define graph (digraph '() (hash (string->keyword name) "value")))
      (define json (read-json (run-dot (digraph->dot graph) "json")))
      (check-equal? (hash-ref json (string->symbol name)) "value"))
    (for ([name '("" "hello world" "node" "a; b" "say \"hello\"" "魚" "back\\slash")])
      (define graph (make-digraph (list (list name '#:label "label"))))
      (define json (read-json (run-dot (digraph->dot graph) "json")))
      (check-equal? (map (lambda (node) (hash-ref node 'name)) (hash-ref json 'objects))
                    (list name)))
    (for ([name '("trailing\\" "slash\\\"quote")])
      (define custom (filled-rectangle 20 20))
      (define graph
        (make-digraph (list (list name '#:shape custom '#:label "")
                            (edge (list (endpoint name #f #f) "target") (hash)))))
      (check-equal? (hash-count (digraph-node-picts graph)) 1)
      (define output (read-json (run-dot (digraph->dot graph) "json")))
      (check-equal? (length (hash-ref output 'objects)) 2)
      (check-true (hash-has-key? (digraph-node-picts graph)
                                (hash-ref (first (hash-ref output 'objects)) 'name))))
    (check-true (pict? (digraph->pict (make-digraph '((edge ("" "a")))))))
    (define graph
      (make-digraph (list '("a:b") '("c")
                          (edge (list (endpoint "a:b" #f #f) "c:n") (hash)))))
    (check-true (pict? (digraph->pict graph)))
    (check-true (pict? (digraph->pict (make-digraph '((same-rank "a"))))))))
