#lang racket
(require rackunit racket/runtime-path "../lib/private/process.rkt")
(define-runtime-path fake "helpers/fake-dot.rkt")
(define racket-bin (find-executable-path "racket"))
(define (fake-run mode [input ""] [timeout 5])
  (execute racket-bin (list (path->string fake) mode) input timeout))
(module+ test
  (check-equal? (fake-run "warning") #"ok")
  (check-exn exn:fail? (lambda () (fake-run "early" (make-string 1000000 #\x))))
  (define directory (make-temporary-file "graphviz-process~a" 'directory))
  (dynamic-wind
    void
    (lambda ()
      (define marker (build-path directory "ready"))
      (define done (make-semaphore))
      (define task
        (thread
         (lambda ()
           (with-handlers ([exn:break? (lambda (_) (semaphore-post done))])
             (execute racket-bin (list (path->string fake) "marker" (path->string marker))
                      "" 5)))))
      (define expiry (+ (current-inexact-monotonic-milliseconds) 5000))
      (let loop ()
        (unless (or (file-exists? marker)
                    (> (current-inexact-monotonic-milliseconds) expiry))
          (sleep 0.01)
          (loop)))
      (check-true (file-exists? marker))
      (break-thread task)
      (check-not-false (sync/timeout 3 done))
      (sleep 1.1)
      (check-false (file-exists? (string-append (path->string marker) ".leaked"))))
    (lambda () (delete-directory/files directory)))
  (check-equal? (fake-run "binary") #"\0\377\200PNG")
  (check-equal? (bytes-length (fake-run "flood" (make-string 200000 #\x))) 200000)
  (check-equal? (bytes->string/utf-8 (fake-run "unicode")) "λ魚")
  (check-exn #rx"status 7.*failure" (lambda () (fake-run "error")))
  (check-exn #rx"timed out" (lambda () (fake-run "sleep" "" 0.2)))
  (check-exn #rx"timed out"
             (lambda () (fake-run "sleep" (make-string 1000000 #\x) 0.2)))
  (check-exn #rx"executable not found"
             (lambda ()
               (parameterize ([current-dot-executable "/missing/graphviz/dot"])
                 (run-dot "digraph {}" "json"))))
  (check-exn exn:fail:contract? (lambda () (run-dot "digraph {}" "png; echo bad")))
  (check-exn exn:fail:contract? (lambda () (current-dot-timeout 0)))
  (when (find-executable-path "dot")
    (define executable (find-executable-path "dot"))
    (define environment (environment-variables-copy (current-environment-variables)))
    (environment-variables-set! environment #"PATH" #"")
    (parameterize ([current-dot-executable executable]
                   [current-environment-variables environment])
      (check-equal? (read-bytes 8 (run-dot "digraph {a->b}" "png"))
                    #"\211PNG\r\n\32\n")
      (check-true (string-contains? (port->string (run-dot "digraph {a->b}" "svg"))
                                    "<svg"))
      (check-exn #rx"Graphviz exited" (lambda () (run-dot "invalid {" "json"))))))
