#lang racket
(require rackunit pict racket/draw json racket/runtime-path
         "../lib/private/render.rkt")
(define-runtime-path fixtures "fixtures")
(define (pixel bitmap x y)
  (define bytes (make-bytes 4))
  (send bitmap get-argb-pixels x y 1 1 bytes)
  bytes)
(module+ test
  (define bitmap (make-bitmap 50 50))
  (define dc (new bitmap-dc% [bitmap bitmap]))
  (send dc set-background "blue")
  (send dc clear)
  (send dc set-brush "red" 'solid)
  (for ([op '("e" "p")])
    (apply-instruction dc
                      (if (equal? op "e")
                          (hash 'op op 'rect '(25 25 10 10))
                          (hash 'op op 'points '((10 10) (40 10) (25 40)))) '())
    (check-equal? (pixel bitmap 25 25) #"\377\0\0\377")
    (check-equal? (send (send dc get-brush) get-style) 'solid))
  (check-equal? (send (string->color "#ff000000") alpha) 0.0)
  (check-equal? (send (string->color "#ff0000") alpha) 1.0)
  (define before (send dc get-transformation))
  (check-exn exn:fail?
             (lambda ()
               (call-with-dc-state dc (lambda () (send dc translate 9 12)
                                        (error 'test "failure")))))
  (check-equal? before (send dc get-transformation))
  (check-exn #rx"unsupported Graphviz"
             (lambda () (apply-instruction dc (hash 'op "I") '())))
  (define empty (xdot-json->pict (hash 'bb "10,40,30,20") (hash)))
  (check-equal? (pict-width empty) 22)
  (check-equal? (pict-height empty) 22)
  (for ([name '("shapes" "labels" "large")])
    (define graph (call-with-input-file (build-path fixtures (string-append name ".json")) read-json))
    (define image (xdot-json->pict graph (hash)))
    (check-true (positive? (pict-width image)))
    (check-true (send (pict->bitmap (scale image 0.5)) ok?))))
