#lang racket
(require rackunit racket/draw "../lib/private/render.rkt")
(module+ test
  (define calls '())
  (define recording-dc%
    (class bitmap-dc%
      (super-new [bitmap (make-bitmap 400 300)])
      (define/override (draw-text text x y [combine #f] [offset 0] [angle 0])
        (set! calls (cons (list text x y) calls)))))
  (define dc (new recording-dc%))
  (define state (make-hasheq))
  (define (draw instruction) (apply-instruction dc instruction state))
  (draw (hash 'op "F" 'size 14 'face "Courier"))
  (check-equal? (send (send dc get-font) get-face) "Courier")
  (check-equal? (send (send dc get-font) get-size) 14.0)
  (check-true (send (send dc get-font) get-size-in-pixels))
  (draw (hash 'op "t" 'fontchar 7))
  (check-equal? (send (send dc get-font) get-weight) 'bold)
  (check-equal? (send (send dc get-font) get-style) 'italic)
  (check-true (send (send dc get-font) get-underlined))
  (check-equal? (send (send dc get-font) get-face) "Courier")
  (draw (hash 'op "t" 'fontchar 0))
  (check-equal? (send (send dc get-font) get-weight) 'normal)
  (check-equal? (send (send dc get-font) get-style) 'normal)
  (check-false (send (send dc get-font) get-underlined))
  (define-values (w h descent space) (send dc get-text-extent "generate-x64"))
  (for ([alignment '("l" "c" "r")] [offset (list 0 (/ w 2) w)])
    (draw (hash 'op "T" 'pt '(100 60) 'align alignment 'width 100
                'text "generate-x64"))
    (check-equal? (car calls) (list "generate-x64" (- 100 offset) (- 60 (- h descent)))))
  (for ([flags '(8 16 32 64 127)])
    (draw (hash 'op "t" 'fontchar flags))
    (draw (hash 'op "T" 'pt '(100 60) 'align "c" 'width 100 'text "label")))
  (draw (hash 'op "t" 'fontchar 0))
  (check-equal? (send (send dc get-font) get-size) 14.0))
